// Additional Scenario-Based Questions - Batch 12 - FINAL BATCH
// Reaching 300 scenario milestone!
// NHTSA 2022 Protocol-Aligned

import { EnhancedQuizQuestion } from './enhanced-quiz-system';

export const additionalFinalScenarios: EnhancedQuizQuestion[] = [
  {
    id: "scenario-final-newborn-delivery-001",
    module: 9,
    chapter: 31,
    scenario: "You just delivered a baby. Infant is breathing, HR 110, but appears cyanotic (blue) especially around face and trunk at 1 minute of life.",
    question: "What is your next action?",
    options: [
      "This is emergency - immediate CPR",
      "Dry, warm, stimulate, provide blow-by oxygen - central cyanosis common initially",
      "Do nothing - completely normal",
      "Suction for 30 seconds"
    ],
    correctAnswer: 1,
    explanation: "Newborn assessment: breathing and HR >100 is good, but central cyanosis needs O2. Dry (stimulates breathing + prevents heat loss), warm, gentle stimulation, blow-by O2 near face. Acrocyanosis (blue hands/feet) is normal, central cyanosis needs oxygen. Most newborns pink up with simple measures.",
    category: "scenario",
    difficulty: "medium",
    tags: ["newborn", "delivery", "neonatal resuscitation", "cyanosis"],
    nremtDomain: "Special Patient Populations",
    nationalProtocolAlignment: "NHTSA 2022 - Neonatal Care Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-apgar-scoring-001",
    module: 9,
    chapter: 31,
    scenario: "At 1 minute after birth: baby has strong cry, HR 130, active motion, grimaces when suctioned, and body is pink but hands/feet slightly blue.",
    question: "What is the APGAR score?",
    options: [
      "7/10",
      "9/10 - Appearance 1, Pulse 2, Grimace 2, Activity 2, Respirations 2",
      "10/10",
      "8/10"
    ],
    correctAnswer: 1,
    explanation: "APGAR scoring (0-2 each): Appearance (1=body pink, extremities blue), Pulse (2=>100), Grimace (2=cry/cough), Activity (2=active), Respirations (2=strong cry). This baby scores 9/10. APGAR done at 1 and 5 minutes. Score guides resuscitation but don't delay care to calculate.",
    category: "scenario",
    difficulty: "medium",
    tags: ["APGAR", "newborn assessment", "scoring"],
    nremtDomain: "Special Patient Populations",
    nationalProtocolAlignment: "NHTSA 2022 - APGAR Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-umbilical-cord-001",
    module: 9,
    chapter: 31,
    scenario: "After delivering baby, when should you clamp and cut the umbilical cord?",
    question: "Current recommendation for cord clamping:",
    options: [
      "Immediately after delivery",
      "Delay 30-60 seconds if baby is vigorous (allows placental transfusion), sooner if resuscitation needed",
      "Never cut cord in field",
      "After 10 minutes"
    ],
    correctAnswer: 1,
    explanation: "Delayed cord clamping (30-60 sec): allows blood transfer from placenta to baby, improves infant outcomes. Place baby on mother's abdomen at level of uterus, dry and stimulate. If baby needs resuscitation, clamp immediately. Clamp in 2 places, cut between clamps.",
    category: "scenario",
    difficulty: "medium",
    tags: ["umbilical cord", "delivery", "delayed clamping"],
    nremtDomain: "Special Patient Populations",
    nationalProtocolAlignment: "NHTSA 2022 - Delayed Cord Clamping Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-needle-stick-001",
    module: 2,
    chapter: 2,
    scenario: "While cleaning equipment, you get stuck by a used needle from unknown patient. Puncture wound is bleeding slightly.",
    question: "What are your immediate actions?",
    options: [
      "Nothing - minor injury",
      "Wash wound with soap/water, report to supervisor immediately, seek medical evaluation, document exposure",
      "Just put bandaid on",
      "Wait to see if symptoms develop"
    ],
    correctAnswer: 1,
    explanation: "Needle stick: wash immediately, report to supervisor, document exposure, seek medical evaluation for baseline testing and possible post-exposure prophylaxis (PEP) for HIV/Hepatitis. Time-sensitive - PEP most effective within hours. Source patient testing if possible. Complete exposure report per protocol.",
    category: "scenario",
    difficulty: "easy",
    tags: ["needle stick", "exposure", "bloodborne pathogens", "PEP"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Exposure Control Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-ppe-selection-001",
    module: 2,
    chapter: 2,
    scenario: "You are called to a patient coughing up blood with suspected tuberculosis.",
    question: "What PPE is required?",
    options: [
      "Gloves only",
      "Gloves, eye protection, N95 respirator (fit-tested) - airborne precautions",
      "Surgical mask is adequate",
      "No PPE needed"
    ],
    correctAnswer: 1,
    explanation: "TB precautions: airborne disease requires N95 respirator (fit-tested), not surgical mask. Also gloves, eye protection. Place surgical mask on patient if tolerated. Notify hospital of TB suspect. If not fit-tested for N95, should not treat. Airborne diseases: TB, measles, chickenpox, COVID.",
    category: "scenario",
    difficulty: "medium",
    tags: ["PPE", "TB", "airborne precautions", "N95"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Infection Control PPE Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-hand-hygiene-001",
    module: 2,
    chapter: 2,
    scenario: "After patient contact, you remove gloves. What is the next critical infection control step?",
    question: "After removing gloves:",
    options: [
      "Nothing else needed",
      "Hand hygiene (wash or alcohol gel) - gloves don't replace handwashing",
      "Just wipe hands on pants",
      "Put on new gloves"
    ],
    correctAnswer: 1,
    explanation: "Hand hygiene: most important infection control measure. After glove removal, hands still contaminated from glove microbreaks, contamination during removal. Wash hands with soap/water (preferred if visibly soiled) or alcohol-based gel. Before and after each patient contact.",
    category: "scenario",
    difficulty: "easy",
    tags: ["hand hygiene", "infection control", "handwashing"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Hand Hygiene Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-consent-competence-001",
    module: 3,
    chapter: 3,
    scenario: "A patient is intoxicated but able to state their name, location, what happened, and clearly refuses transport. Glucose normal, no injuries.",
    question: "Can this patient refuse?",
    options: [
      "No - intoxication always means incompetent",
      "Possibly - assess decision-making capacity (understands situation/risks), intoxication alone doesn't equal incompetence, contact medical direction",
      "Yes - always let patients refuse",
      "Force transport"
    ],
    correctAnswer: 1,
    explanation: "Competence to refuse: patient must understand their condition, risks of refusal, and consequences. Intoxication doesn't automatically equal incompetence. Assess mental status, decision-making ability. Document thoroughly. Contact medical direction with borderline cases. When in doubt, encourage transport.",
    category: "scenario",
    difficulty: "hard",
    tags: ["consent", "refusal", "competence", "intoxication"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Consent Competence Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-final-scene-size-up-001",
    module: 4,
    chapter: 7,
    scenario: "Dispatch reports 'man down' at residence. You arrive to find front door open, glass broken, yelling heard inside.",
    question: "What is your first action?",
    options: [
      "Enter immediately to help patient",
      "Stage at safe distance, request police, do not enter until scene secured",
      "Knock and announce presence",
      "Scene safety doesn't matter when someone needs help"
    ],
    correctAnswer: 1,
    explanation: "Scene safety first: violence/crime scene indicators (broken glass, yelling, unknown 'man down') require staging for police. Dead providers can't help patients. Never compromise crew safety. Stage at safe distance out of sight, wait for scene secure from police. Reassess safety continuously.",
    category: "scenario",
    difficulty: "easy",
    tags: ["scene safety", "staging", "violence", "crew safety"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Scene Safety Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-hazmat-awareness-001",
    module: 10,
    chapter: 37,
    scenario: "You arrive at industrial facility for 'multiple sick employees.' You notice strange odor, multiple patients with similar symptoms (nausea, dizziness), and placards on building indicating chemicals stored.",
    question: "What should you do?",
    options: [
      "Enter and treat patients",
      "Recognize hazmat incident, establish safe perimeter uphill/upwind, request hazmat team, don't enter",
      "Move all patients outside yourself",
      "Hazmat is firefighter problem only"
    ],
    correctAnswer: 1,
    explanation: "Hazmat recognition: multiple patients, similar symptoms, chemical smell/placards, industrial setting = hazmat incident. EMS awareness level: recognize, isolate (safe perimeter uphill/upwind), notify hazmat team. Don't enter hot zone. Only decontaminated patients can be treated. Protect yourself and crew.",
    category: "scenario",
    difficulty: "medium",
    tags: ["hazmat", "scene safety", "awareness level", "decontamination"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Hazmat Awareness Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-active-shooter-001",
    module: 10,
    chapter: 37,
    scenario: "Dispatch reports active shooter at school. First responders (police) are making entry. You are requested to stage.",
    question: "When can EMS enter?",
    options: [
      "Immediately - people need help",
      "Only after law enforcement declares scene secure or establishes safe corridor (warm zone)",
      "With police escort into active scene",
      "EMS doesn't respond to shootings"
    ],
    correctAnswer: 1,
    explanation: "Active shooter/violence: EMS stages at safe location until law enforcement secures scene or establishes warm zone. Tactical EMS or RTF (Rescue Task Force) may operate in warm zone with police protection. Never enter hot zone (active threat). Patient care occurs in cold/warm zones only. Crew safety paramount.",
    category: "scenario",
    difficulty: "medium",
    tags: ["active shooter", "tactical EMS", "staging", "scene security"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Active Threat Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-confined-space-001",
    module: 10,
    chapter: 37,
    scenario: "Worker collapsed in industrial tank. Co-worker went in to rescue and also collapsed. You arrive and family begs you to enter tank to save them.",
    question: "What should you recognize?",
    options: [
      "Enter immediately with oxygen",
      "Confined space emergency - oxygen deficiency/toxins, don't enter, request specialized rescue, prevent more victims",
      "Use a rope to pull them out",
      "Send in police"
    ],
    correctAnswer: 1,
    explanation: "Confined space: limited entry/exit, not designed for continuous occupancy. Multiple victims in confined space = oxygen deficiency or toxic gas. Secondary victim (rescuer) classic pattern. Don't become victim - request specialized rescue with air monitoring and SCBA. Prevent others from entering.",
    category: "scenario",
    difficulty: "medium",
    tags: ["confined space", "oxygen deficiency", "specialized rescue"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Confined Space Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-electrical-injury-001",
    module: 8,
    chapter: 23,
    scenario: "Worker contacted electrical wire and is still in contact with wire. Wire is on ground near patient.",
    question: "What is your first priority?",
    options: [
      "Pull patient away from wire",
      "Ensure power is off, do not touch patient or wire until power secured, request power company",
      "Use wooden stick to move wire",
      "Provide immediate CPR"
    ],
    correctAnswer: 1,
    explanation: "Electrical emergency: don't touch patient until power off - you'll become another victim. Request power company, don't approach energized wires. After power confirmed off, assess patient for cardiac arrest (electrical shock causes VF), entry/exit burns, spinal injury. Internal injuries often worse than visible burns.",
    category: "scenario",
    difficulty: "easy",
    tags: ["electrical injury", "scene safety", "power lines"],
    nremtDomain: "Trauma",
    nationalProtocolAlignment: "NHTSA 2022 - Electrical Emergency Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-agriculture-entrapment-001",
    module: 10,
    chapter: 37,
    scenario: "Farmer is trapped in grain bin with grain up to chest level and continuing to sink. Patient is conscious and calling for help.",
    question: "What specialized rescue is needed?",
    options: [
      "Just pull patient out",
      "Grain bin rescue team - engulfment risk, specialized equipment needed to stop grain flow and extricate safely",
      "Have patient swim out",
      "Send someone else in to dig"
    ],
    correctAnswer: 1,
    explanation: "Grain bin rescue: grain acts like quicksand - victim sinks, grain compresses making breathing difficult and extraction nearly impossible without equipment. Don't enter - rescuers become trapped. Request specialized agricultural rescue with grain vacuum/rescue tubes. Time-critical but requires proper resources.",
    category: "scenario",
    difficulty: "medium",
    tags: ["agricultural rescue", "grain entrapment", "specialized rescue"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Agricultural Emergency Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-multiple-patients-001",
    module: 10,
    chapter: 38,
    scenario: "You arrive first to 2-car MVC with 6 patients. You have one ambulance and one partner.",
    question: "What is your immediate priority?",
    options: [
      "Start treating most serious patient",
      "Rapid triage of all patients, call for additional resources, identify life threats, organize scene",
      "Transport first patient you find",
      "Wait for more help"
    ],
    correctAnswer: 1,
    explanation: "Multiple patient management: rapid triage all patients first (START if MCI), identify life threats, call for adequate resources early, organize scene. Don't get focused on one patient while others deteriorate. Establish command, request needed resources, begin systematic treatment based on priority.",
    category: "scenario",
    difficulty: "medium",
    tags: ["multiple patients", "triage", "resource management", "scene organization"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Multiple Patient Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-patient-belongings-001",
    module: 3,
    chapter: 6,
    scenario: "Critical patient's wallet, jewelry, and phone are left at scene. Family members want to take belongings.",
    question: "How should you handle patient property?",
    options: [
      "Leave everything at scene",
      "Secure patient valuables, document on PCR, give to hospital or law enforcement per protocol, get witness signature",
      "Give to family immediately",
      "Take home for safekeeping"
    ],
    correctAnswer: 1,
    explanation: "Patient property: secure valuables, document specifically on PCR (witness if possible), transport with patient or secure per protocol. Don't leave at unsecured scene. Don't give to family without patient consent (unless patient is deceased). Document chain of custody. Protect yourself from false accusations.",
    category: "scenario",
    difficulty: "easy",
    tags: ["patient property", "valuables", "documentation"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Property Management Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-death-notification-001",
    module: 3,
    chapter: 4,
    scenario: "Patient dies during resuscitation. Family is on scene asking about patient status.",
    question: "How should you communicate?",
    options: [
      "Say 'he's dead' bluntly",
      "Use clear, compassionate language - avoid euphemisms, use 'died' or 'death,' provide support, notify medical examiner if appropriate",
      "Avoid telling family directly",
      "Use only medical terms"
    ],
    correctAnswer: 1,
    explanation: "Death notification: compassionate but clear. Use 'died' or 'death' (not 'passed away,' 'lost') to avoid confusion. Explain briefly what happened, allow family time to process, offer to contact support persons. Follow protocols for medical examiner notification if unnatural death. Show empathy but be honest.",
    category: "scenario",
    difficulty: "medium",
    tags: ["death notification", "family communication", "grief support"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Death Notification Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-stress-management-001",
    module: 2,
    chapter: 2,
    scenario: "After particularly traumatic pediatric call, you notice partner is withdrawn, not eating, having nightmares, and avoiding talking about the call.",
    question: "These could be signs of:",
    options: [
      "Normal - will pass on its own",
      "Critical Incident Stress or PTSD - encourage use of CISM resources, peer support, mental health services",
      "Weakness",
      "Nothing concerning"
    ],
    correctAnswer: 1,
    explanation: "Critical Incident Stress: nightmares, withdrawal, appetite changes, avoidance after traumatic call can indicate CISM or PTSD. Encourage use of CISM debriefing, peer support, EAP, mental health services. Not weakness - normal response to abnormal event. Early intervention prevents chronic issues. Take care of yourself and crew.",
    category: "scenario",
    difficulty: "easy",
    tags: ["CISM", "PTSD", "stress management", "mental health"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Provider Wellness Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-quality-improvement-001",
    module: 3,
    chapter: 1,
    scenario: "Your EMS system is implementing new protocol for chest pain. Medical director requests PCR reviews and feedback from field providers.",
    question: "This is an example of:",
    options: [
      "Punishment system",
      "Quality Improvement/Quality Assurance process to improve patient care",
      "Waste of time",
      "Medical director being difficult"
    ],
    correctAnswer: 1,
    explanation: "QI/QA: systematic review of care to identify improvement opportunities. PCR reviews, case studies, protocol updates based on evidence and experience. Not punitive (unless negligence) - goal is system improvement. Provider input valuable. Continuous quality improvement improves patient outcomes.",
    category: "scenario",
    difficulty: "easy",
    tags: ["QI", "QA", "quality improvement", "protocols"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Quality Improvement Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-scope-practice-001",
    module: 3,
    chapter: 1,
    scenario: "A paramedic partner asks you (EMT) to start an IV on a patient because they're busy with another intervention.",
    question: "What should you do?",
    options: [
      "Start the IV - it's easy",
      "Decline - starting IVs is outside EMT scope of practice, offer to help within your scope",
      "Try it and see",
      "Paramedics can delegate anything"
    ],
    correctAnswer: 1,
    explanation: "Scope of practice: defined by state law, training, medical direction, protocols. Cannot perform skills outside scope even if asked/trained informally. IV therapy outside most EMT scopes. Offer appropriate assistance. Operating beyond scope = license risk, liability, patient harm potential. Know your scope limits.",
    category: "scenario",
    difficulty: "easy",
    tags: ["scope of practice", "EMT limitations", "legal"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Scope of Practice Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-ems-systems-001",
    module: 1,
    chapter: 1,
    scenario: "Your medical director reviews your PCRs, provides feedback on patient care, and updates protocols based on current evidence.",
    question: "This represents which EMS system component?",
    options: [
      "Online medical direction only",
      "Offline (indirect) medical direction - supervision, protocol development, QI, education",
      "Punishment",
      "Dispatch function"
    ],
    correctAnswer: 1,
    explanation: "Offline medical direction: physician oversight including protocol development, training, QI, PCR review, system medical policies. Online (direct) = real-time orders by radio/phone. Medical director responsible for medical aspects of EMS system. Ensures quality, appropriate care, evidence-based practice.",
    category: "scenario",
    difficulty: "easy",
    tags: ["medical direction", "EMS systems", "offline direction"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Medical Direction Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-online-med-control-001",
    module: 1,
    chapter: 1,
    scenario: "You contact medical control by radio for orders to assist with a medication not specifically in your protocols for this presentation.",
    question: "This is example of:",
    options: [
      "Offline medical direction",
      "Online (direct) medical direction - real-time physician orders",
      "Protocol violation",
      "Dispatch"
    ],
    correctAnswer: 1,
    explanation: "Online medical direction: real-time physician orders via radio/phone for situations outside protocols or requiring physician judgment. Repeat orders back (echo), clarify if unclear, document. Different than offline direction (standing protocols, QI, education). Use when protocol doesn't cover situation or requires physician decision.",
    category: "scenario",
    difficulty: "easy",
    tags: ["online medical direction", "physician orders", "medical control"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Online Medical Control Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-research-consent-001",
    module: 3,
    chapter: 3,
    scenario: "Your EMS agency is participating in research study. You respond to cardiac arrest which meets study criteria. Protocol allows enrollment without consent in emergency.",
    question: "This represents:",
    options: [
      "Illegal research",
      "Exception from informed consent (EFIC) for emergency research when consent not feasible",
      "Always need consent for research",
      "Unethical"
    ],
    correctAnswer: 1,
    explanation: "Emergency research: FDA/IRB can approve Exception from Informed Consent (EFIC) for emergency research when: life-threatening condition, available treatments unsatisfactory, can't get consent, family notification when possible, community consultation done. Strict oversight. Advances emergency care knowledge.",
    category: "scenario",
    difficulty: "hard",
    tags: ["research", "EFIC", "consent", "ethics"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Research Ethics Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-final-mass-casualty-planning-001",
    module: 10,
    chapter: 38,
    scenario: "Bus crash with 30 patients. You are first arriving unit. Radio traffic indicates multiple other calls in system - resources will be delayed.",
    question: "What system should you implement?",
    options: [
      "Treat patients one at a time",
      "Declare MCI, establish ICS, request mutual aid, begin START triage, organize treatment/transport",
      "Wait for supervisor",
      "Transport whoever you can fit"
    ],
    correctAnswer: 1,
    explanation: "MCI management: declare early, establish Incident Command System (ICS), request adequate resources/mutual aid, begin systematic triage (START), establish treatment areas, coordinate transport. First arriving unit often becomes IC until relieved. Organize before treating. Use triage tags. System approach saves most lives.",
    category: "scenario",
    difficulty: "medium",
    tags: ["MCI", "ICS", "incident command", "mass casualty"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - MCI Management Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-resource-allocation-001",
    module: 10,
    chapter: 38,
    scenario: "MCI with limited ambulances. You have 2 red (immediate), 5 yellow (delayed), and 10 green (minor) patients. One ambulance available.",
    question: "Who gets first transport?",
    options: [
      "Green patients - they can walk",
      "Red (immediate) patients - highest priority, most likely to benefit from rapid transport",
      "Yellow patients",
      "Whoever is closest"
    ],
    correctAnswer: 1,
    explanation: "MCI transport priority: RED first (immediate - critical but salvageable), then YELLOW (delayed - serious but stable), then GREEN (minor - walking wounded), BLACK last if resources allow (expectant/deceased). Maximize lives saved with limited resources. Different than normal care where all get immediate transport.",
    category: "scenario",
    difficulty: "easy",
    tags: ["MCI", "transport priority", "resource allocation"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - MCI Transport Priority Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-incident-command-001",
    module: 10,
    chapter: 38,
    scenario: "You are first arriving unit at MCI. Fire department arrives shortly after and wants to take over as Incident Commander.",
    question: "What should happen?",
    options: [
      "Refuse - you were first",
      "Transfer command with face-to-face briefing of situation, actions taken, resources needed",
      "Both be in command",
      "No formal transfer needed"
    ],
    correctAnswer: 1,
    explanation: "ICS command transfer: formal face-to-face transfer when command changes. Brief incoming IC on situation, actions taken, resources ordered, current priorities. Document transfer. Usually first arriving becomes IC, then transfers to appropriate agency/rank. Clear chain of command prevents confusion. Get briefing before assuming command.",
    category: "scenario",
    difficulty: "easy",
    tags: ["ICS", "incident command", "command transfer"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - ICS Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-weapons-mass-destruction-001",
    module: 10,
    chapter: 37,
    scenario: "Multiple patients at shopping mall with sudden onset of difficulty breathing, excessive salivation, pinpoint pupils, and muscle fasciculations. No apparent cause visible.",
    question: "You should suspect:",
    options: [
      "Food poisoning",
      "Possible WMD/nerve agent - recognize SLUDGEM symptoms, request hazmat, don't enter, decon required",
      "Carbon monoxide",
      "Normal illness cluster"
    ],
    correctAnswer: 1,
    explanation: "WMD/nerve agent recognition: SLUDGEM symptoms, multiple simultaneous patients, no obvious cause = possible chemical/nerve agent. Don't enter - become victim. Request hazmat, law enforcement, specialized resources. Victims need decontamination before treatment. Awareness level: recognize, isolate, notify. EMS doesn't enter hot zone.",
    category: "scenario",
    difficulty: "hard",
    tags: ["WMD", "nerve agent", "SLUDGEM", "chemical weapon"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - WMD Awareness Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-final-pandemic-response-001",
    module: 2,
    chapter: 2,
    scenario: "During respiratory pandemic, you respond to patient with fever, cough, and difficulty breathing. Patient not wearing mask.",
    question: "What PPE is appropriate?",
    options: [
      "No PPE needed",
      "N95 respirator, eye protection, gloves, gown for droplet/airborne precautions",
      "Gloves only",
      "Surgical mask adequate for all respiratory illnesses"
    ],
    correctAnswer: 1,
    explanation: "Pandemic respiratory illness PPE: N95 respirator (airborne), eye protection (goggles/face shield), gloves, gown. Higher level than routine respiratory illness during pandemic. Follow CDC/local guidance. Place mask on patient if tolerated. Decontaminate ambulance thoroughly. Monitor for symptoms post-exposure.",
    category: "scenario",
    difficulty: "medium",
    tags: ["pandemic", "PPE", "respiratory precautions", "infection control"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Pandemic Response Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-public-health-001",
    module: 2,
    chapter: 2,
    scenario: "You notice unusual cluster of patients with similar GI symptoms from same restaurant over several shifts.",
    question: "What should you do?",
    options: [
      "Nothing - not your concern",
      "Report pattern to supervisor/public health - possible outbreak requiring investigation",
      "Tell restaurant owner only",
      "Wait for more patients"
    ],
    correctAnswer: 1,
    explanation: "Public health surveillance: EMS often first to recognize disease clusters/outbreaks. Report unusual patterns to supervisor and public health. Could be foodborne illness, biological agent, environmental exposure. Early recognition enables public health intervention. EMS is part of public health system.",
    category: "scenario",
    difficulty: "easy",
    tags: ["public health", "disease surveillance", "outbreak"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Public Health Surveillance Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-pediatric-equipment-001",
    module: 9,
    chapter: 30,
    scenario: "You need to choose appropriate equipment for 3-year-old. What sizing method can help?",
    question: "Pediatric equipment sizing:",
    options: [
      "Guess based on appearance",
      "Length-based tape (Broselow), weight-based calculations, or age-based formulas",
      "Use adult equipment on all children",
      "All 3-year-olds use same size"
    ],
    correctAnswer: 1,
    explanation: "Pediatric sizing: length-based tape (Broselow) most accurate - matches height to weight/equipment/drug doses. Age-based formulas less accurate but quick (ETT = age/4 + 4). Weight if known. Children vary widely - size equipment appropriately. BP cuff 2/3 upper arm, mask covers nose/mouth not eyes.",
    category: "scenario",
    difficulty: "easy",
    tags: ["pediatric equipment", "Broselow tape", "sizing"],
    nremtDomain: "Special Patient Populations",
    nationalProtocolAlignment: "NHTSA 2022 - Pediatric Equipment Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-cultural-competence-001",
    module: 3,
    chapter: 4,
    scenario: "Patient's family asks you to not tell patient about cancer diagnosis because in their culture, family protects patient from bad news.",
    question: "How should you handle this?",
    options: [
      "Immediately tell patient despite family wishes",
      "Respect cultural differences, involve medical direction, balance patient autonomy with cultural sensitivity",
      "Always defer to family",
      "Ignore cultural factors"
    ],
    correctAnswer: 1,
    explanation: "Cultural competence: recognize different cultural approaches to illness/death/truth-telling. Balance patient right to know with family cultural practices. Involve medical direction for ethical guidance. Be respectful and non-judgmental. In emergency, focus on immediate care. Can address complex issues at hospital with ethics consult.",
    category: "scenario",
    difficulty: "hard",
    tags: ["cultural competence", "ethics", "patient autonomy"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Cultural Competence Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-final-continuous-education-001",
    module: 1,
    chapter: 1,
    scenario: "To maintain your EMT certification, what is required?",
    question: "EMT recertification typically requires:",
    options: [
      "Nothing - certification is permanent",
      "Continuing education hours and/or refresher course every 2-3 years (varies by state)",
      "Just paying fee",
      "One-time certification"
    ],
    correctAnswer: 1,
    explanation: "EMT recertification: required every 2-3 years (state-dependent). Need continuing education (CE) hours and/or refresher course. Keeps skills current, updates to new protocols/evidence. National Registry uses continuing education model. Maintain CPR certification. Check state requirements. Failure to recertify = expired certification, can't practice.",
    category: "scenario",
    difficulty: "easy",
    tags: ["certification", "continuing education", "recertification"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Certification Maintenance Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-ems-roles-001",
    module: 1,
    chapter: 1,
    scenario: "What is a primary role of the EMT?",
    question: "EMT primary responsibilities include:",
    options: [
      "Diagnosing diseases",
      "Providing emergency medical care, patient assessment, safe transport, and patient advocacy",
      "Prescribing medications",
      "Performing surgery"
    ],
    correctAnswer: 1,
    explanation: "EMT roles: emergency medical care (BLS level), patient assessment, treatment within scope, safe transport, patient advocacy, communication, documentation. Don't diagnose (identify presentations), don't prescribe (assist with patient's own meds). Link between incident and hospital. Professional, compassionate, competent care.",
    category: "scenario",
    difficulty: "easy",
    tags: ["EMT roles", "scope", "responsibilities"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - EMT Roles Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-nremt-domains-001",
    module: 1,
    chapter: 1,
    scenario: "The National Registry of EMTs (NREMT) cognitive exam tests knowledge across several domains. What are the main domains?",
    question: "NREMT testing domains include:",
    options: [
      "Only trauma",
      "Airway/Respiration, Cardiology, Trauma, Medical, OB/Peds, EMS Operations",
      "Only medical emergencies",
      "Only operations"
    ],
    correctAnswer: 1,
    explanation: "NREMT domains: Airway/Respiration/Ventilation, Cardiology/Resuscitation, Trauma, Medical/OB/GYN, EMS Operations. Adaptive test adjusts difficulty. Comprehensive coverage of EMT knowledge. Also requires psychomotor exam (skills testing). Certification demonstrates minimum competency standard nationwide.",
    category: "scenario",
    difficulty: "easy",
    tags: ["NREMT", "testing domains", "certification"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - NREMT Standards",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-ems-history-001",
    module: 1,
    chapter: 1,
    scenario: "Modern EMS systems evolved significantly after which landmark legislation?",
    question: "What legislation shaped modern EMS?",
    options: [
      "No specific legislation",
      "1966 'Accidental Death and Disability: The Neglected Disease of Modern Society' (White Paper) and Highway Safety Act of 1966",
      "Just local initiatives",
      "Always existed in current form"
    ],
    correctAnswer: 1,
    explanation: "EMS history: 1966 White Paper highlighted poor emergency care, led to Highway Safety Act creating EMS standards. Before this, hearses transported patients with minimal care. Evolution: WWI-WWII military medicine, 1960s paramedic programs, 1973 EMS Systems Act, ongoing improvements. Now sophisticated, evidence-based, professional systems.",
    category: "scenario",
    difficulty: "medium",
    tags: ["EMS history", "White Paper", "legislation"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - EMS History",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-levels-of-training-001",
    module: 1,
    chapter: 1,
    scenario: "What are the nationally recognized levels of EMS providers in order of training?",
    question: "EMS provider levels (NHTSA model):",
    options: [
      "Only EMT exists",
      "Emergency Medical Responder (EMR), EMT, Advanced EMT (AEMT), Paramedic",
      "Only Paramedic level matters",
      "No standard levels"
    ],
    correctAnswer: 1,
    explanation: "EMS levels (increasing scope): EMR (First Responder - basic care), EMT (basic life support), AEMT (limited advanced skills - IV, some meds), Paramedic (advanced life support - full scope). Each level has defined scope. Some states have variations. Tiered system provides appropriate care level.",
    category: "scenario",
    difficulty: "easy",
    tags: ["EMS levels", "EMT", "Paramedic", "AEMT"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Provider Levels",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-professionalism-001",
    module: 1,
    chapter: 1,
    scenario: "You arrive at scene before patient, have time to prepare. What demonstrates professionalism?",
    question: "Professional appearance and behavior includes:",
    options: [
      "Wearing whatever is comfortable",
      "Clean uniform, good hygiene, equipment ready, respectful demeanor, competent care",
      "Professionalism doesn't matter",
      "Just technical skills matter"
    ],
    correctAnswer: 1,
    explanation: "EMS professionalism: clean/proper uniform, good hygiene, equipment maintained/ready, respectful behavior, patient-focused, competent care, ongoing education, ethical conduct, good communication. First impression matters. Professionalism builds patient trust and public confidence in EMS. Represent profession and agency.",
    category: "scenario",
    difficulty: "easy",
    tags: ["professionalism", "appearance", "conduct"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Professional Conduct",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-evidence-based-practice-001",
    module: 1,
    chapter: 1,
    scenario: "Your protocols were just updated based on new research showing certain treatment is more effective. What is this an example of?",
    question: "This represents:",
    options: [
      "Random change",
      "Evidence-based practice - using current research to guide patient care",
      "Medical director preference only",
      "Unnecessary change"
    ],
    correctAnswer: 1,
    explanation: "Evidence-based practice (EBP): using best current evidence from research to guide clinical decisions and protocols. EMS protocols should be based on scientific evidence, not just tradition. Research continues to improve care - CPR guidelines, medication protocols, equipment use. Stay current with evidence. EMS is evolving science.",
    category: "scenario",
    difficulty: "easy",
    tags: ["evidence-based practice", "research", "protocols"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Evidence-Based Practice",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-patient-outcomes-001",
    module: 1,
    chapter: 1,
    scenario: "What is the ultimate goal of prehospital care?",
    question: "Primary goal of EMS:",
    options: [
      "Fast transport only",
      "Improve patient outcomes through appropriate assessment, treatment, and transport to right facility",
      "Just follow protocols mechanically",
      "Get patient off your hands"
    ],
    correctAnswer: 1,
    explanation: "EMS goal: improve patient outcomes - reduce death, disability, suffering. Requires appropriate assessment, evidence-based treatment, right hospital/right time, competent care, compassionate service. Not just transport service - medical care providers. Focus on what's best for patient. Measure success by patient outcomes, not just response times.",
    category: "scenario",
    difficulty: "easy",
    tags: ["patient outcomes", "EMS goals", "quality care"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Patient-Centered Care",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-ems-system-components-001",
    module: 1,
    chapter: 1,
    scenario: "A comprehensive EMS system includes many components working together. Which are essential components?",
    question: "EMS system components include:",
    options: [
      "Only ambulances",
      "Regulations, resources, education, medical direction, communications, facilities, data/QI, public education",
      "Just 911 dispatch",
      "Only hospital emergency departments"
    ],
    correctAnswer: 1,
    explanation: "EMS system components: regulation/legislation, resource management, human resources/training, transportation, facilities, communications, public information/education, medical direction, trauma systems, evaluation/quality improvement. Integrated system - all components must work together. EMS is complex system, not just ambulances.",
    category: "scenario",
    difficulty: "medium",
    tags: ["EMS systems", "system components", "integration"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - EMS Systems",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-mobile-integrated-health-001",
    module: 1,
    chapter: 1,
    scenario: "Your EMS agency is providing community paramedicine services - home visits for high-risk patients, chronic disease management, and preventing unnecessary 911 calls.",
    question: "This represents:",
    options: [
      "Not real EMS work",
      "Mobile Integrated Healthcare/Community Paramedicine - evolving EMS role in public health",
      "Only ALS role",
      "Insurance fraud"
    ],
    correctAnswer: 1,
    explanation: "Mobile Integrated Healthcare (MIH)/Community Paramedicine: expanding EMS beyond emergency response to community health, chronic disease management, preventive care, post-discharge follow-up. Reduces hospital readmissions, improves outcomes, prevents 911 abuse. Evolution of EMS as community healthcare resource. Requires additional training.",
    category: "scenario",
    difficulty: "medium",
    tags: ["MIH", "community paramedicine", "public health"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - MIH/Community Paramedicine",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-resilience-wellness-001",
    module: 2,
    chapter: 2,
    scenario: "To maintain long-term health and prevent burnout in EMS career, what strategies are important?",
    question: "Provider wellness and resilience includes:",
    options: [
      "Just work harder",
      "Physical fitness, mental health care, work-life balance, peer support, seeking help when needed",
      "Ignore stress",
      "Wellness doesn't matter"
    ],
    correctAnswer: 1,
    explanation: "EMS wellness: physical fitness, nutrition, sleep, mental health, stress management, work-life balance, peer support, family time, hobbies. High-stress profession requires active wellness maintenance. Seeking help is strength not weakness. CISM, EAP, counseling available. Career longevity requires taking care of yourself. Can't help others if you're broken.",
    category: "scenario",
    difficulty: "easy",
    tags: ["wellness", "resilience", "burnout prevention", "self-care"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Provider Wellness",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-lifting-mechanics-001",
    module: 2,
    chapter: 5,
    scenario: "You need to lift a heavy patient from floor to stretcher. What technique prevents back injury?",
    question: "Proper lifting technique includes:",
    options: [
      "Bend at waist, use back muscles",
      "Legs shoulder-width apart, bend knees, keep back straight, lift with legs not back, hold load close",
      "Twist while lifting",
      "Lift alone to prove strength"
    ],
    correctAnswer: 1,
    explanation: "Safe lifting: power grip, feet shoulder-width apart, bend knees (not waist), back straight, lift with leg muscles, keep weight close to body, avoid twisting, use team lifts for heavy loads. Back injuries common in EMS. Use equipment (stair chair, lift assists) when available. Don't risk injury - get help.",
    category: "scenario",
    difficulty: "easy",
    tags: ["lifting", "body mechanics", "back safety"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Safe Lifting Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-restraint-use-001",
    module: 7,
    chapter: 19,
    scenario: "Violent patient requires restraints for safety. What principles must you follow?",
    question: "Safe restraint application requires:",
    options: [
      "Apply restraints alone",
      "Adequate personnel (5-6), humane restraints, monitor airway/circulation, position safely (not prone), document thoroughly, law enforcement present",
      "Prone position acceptable",
      "Restraints don't need monitoring"
    ],
    correctAnswer: 1,
    explanation: "Restraint safety: adequate team (5-6 people), law enforcement present, humane restraints (soft), supine or side-lying (not prone - positional asphyxia risk), monitor circulation/airway, continuous observation, document medical necessity and monitoring. Last resort after de-escalation fails. Restraint use is high-risk.",
    category: "scenario",
    difficulty: "medium",
    tags: ["restraints", "behavioral emergency", "positional asphyxia"],
    nremtDomain: "Medical",
    nationalProtocolAlignment: "NHTSA 2022 - Safe Restraint Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-final-oxygen-device-selection-001",
    module: 5,
    chapter: 10,
    scenario: "Patient needs high-flow oxygen. Which device delivers highest concentration?",
    question: "Oxygen delivery device capabilities:",
    options: [
      "Nasal cannula - 24-44%",
      "Nonrebreather mask with reservoir at 15 LPM - up to 90-95%",
      "Simple face mask - 35-60%",
      "All devices equal"
    ],
    correctAnswer: 1,
    explanation: "Oxygen devices: nasal cannula 1-6 LPM (24-44%), simple mask 6-10 LPM (35-60%), nonrebreather with reservoir 15 LPM (90-95%). Nonrebreather highest concentration for spontaneously breathing. BVM with O2 can achieve near 100%. Select device based on patient need. Ensure reservoir bag doesn't collapse during inhalation.",
    category: "scenario",
    difficulty: "easy",
    tags: ["oxygen therapy", "NRB", "oxygen devices"],
    nremtDomain: "Airway Management",
    nationalProtocolAlignment: "NHTSA 2022 - Oxygen Delivery Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-medication-six-rights-001",
    module: 4,
    chapter: 11,
    scenario: "Before assisting patient with any medication, what must you verify?",
    question: "Six Rights of medication administration:",
    options: [
      "Just give whatever patient asks for",
      "Right patient, Right medication, Right dose, Right route, Right time, Right documentation",
      "Medications don't need verification",
      "Only check medication name"
    ],
    correctAnswer: 1,
    explanation: "Six Rights: Right PATIENT (is it theirs?), Right MEDICATION (check label/expiration), Right DOSE (correct amount), Right ROUTE (oral/sublingual/inhaled/injected), Right TIME (appropriate now? not expired?), Right DOCUMENTATION (record what was given). Prevents medication errors. Check multiple times. If any doubt, contact medical direction.",
    category: "scenario",
    difficulty: "easy",
    tags: ["medication administration", "six rights", "medication safety"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Medication Safety Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-special-needs-children-001",
    module: 9,
    chapter: 32,
    scenario: "Child with cerebral palsy has tracheostomy and gastrostomy tube. Parents are experts in child's care and equipment. How should you approach this?",
    question: "Managing special needs patients:",
    options: [
      "Ignore parents - you're the expert",
      "Listen to parents/caregivers - they know child's baseline and equipment, incorporate their expertise",
      "Treat exactly like all other children",
      "Special equipment is too complicated"
    ],
    correctAnswer: 1,
    explanation: "Special healthcare needs: parents/caregivers are experts in their child's specific needs, baseline, equipment. Listen to them! Ask about child's normal status, how current differs, how equipment works, what works for this child. Use their knowledge. Many have better medical understanding than providers. Respectful partnership improves care.",
    category: "scenario",
    difficulty: "easy",
    tags: ["special needs", "pediatric", "caregiver partnership"],
    nremtDomain: "Special Patient Populations",
    nationalProtocolAlignment: "NHTSA 2022 - Special Needs Protocol",
    emtScopeCompliant: true,
    points: 2,
    timeEstimate: 60
  },
  {
    id: "scenario-final-congratulations-300-001",
    module: 1,
    chapter: 1,
    scenario: "You have completed all 300 scenario-based practice questions covering every aspect of EMT-B knowledge! From basic life support to complex multi-system emergencies, trauma to medical, pediatrics to geriatrics, and EMS operations to legal/ethical issues.",
    question: "What have you accomplished?",
    options: [
      "Nothing significant",
      "Comprehensive review of EMT curriculum through realistic scenarios - excellent NREMT preparation!",
      "Wasted time",
      "Just memorized answers"
    ],
    correctAnswer: 1,
    explanation: "CONGRATULATIONS! You've completed 300 comprehensive, medically-accurate, protocol-aligned EMT scenarios. This deep practice builds clinical reasoning, critical thinking, and real-world application skills essential for both the NREMT exam and actual patient care. Combined with 450 knowledge questions, you have 750 total questions mastered. You're well-prepared! Remember: stay calm, read carefully, think through scenarios systematically, and trust your training. You've got this! Good luck on your NREMT and welcome to the EMS profession! 🚑",
    category: "scenario",
    difficulty: "easy",
    tags: ["congratulations", "completion", "NREMT prep", "confidence"],
    nremtDomain: "EMS Operations",
    nationalProtocolAlignment: "NHTSA 2022 - Comprehensive Competency",
    emtScopeCompliant: true,
    points: 5,
    timeEstimate: 60
  }
];
