// Additional Scenario-Based Questions - Batch 11
// Approaching 300 scenario milestone
// NHTSA 2022 Protocol-Aligned

import { EnhancedQuizQuestion } from './enhanced-quiz-system';

export const additionalIntegratedScenariosSet1: EnhancedQuizQuestion[] = [
  {
    id: "scenario-integrated-multi-trauma-001",
    module: 8,
    chapter: 28,
    scenario: "MVC patient has open femur fracture with severe bleeding, decreased LOC, and respiratory distress. You are alone with patient for 2 minutes until partner arrives.",
    question: "What is your first priority?",
    options: [
      "Splint femur",
      "Control life-threatening bleeding first, then airway/breathing",
      "Take full set of vital signs",
      "Wait for partner"
    ],
    correctAnswer: 1,
    explanation: "Multi-system trauma priorities: catastrophic hemorrhage first (can die in minutes), then airway, breathing, circulation. Uncontrolled arterial bleeding kills faster than airway compromise. Control bleeding, then address airway/breathing, then other injuries.",
    category: "scenario",
    difficulty: "hard",
    tags: ["multi-system trauma", "prioritization", "ABC vs CAB"],
    nremtDomain: "Trauma",
    nationalProtocolAlignment: "NHTSA 2022 - Trauma Prioritization Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-integrated-cardiac-resp-001",
    module: 7,
    chapter: 15,
    scenario: "Patient has chest pain AND severe respiratory distress with crackles bilaterally. History of CHF and prior MI. BP 160/100, HR 110, RR 32, SpO2 88%.",
    question: "This patient likely has:",
    options: [
      "Separate cardiac and respiratory problems",
      "Acute pulmonary edema from cardiac failure - both symptoms from same cause",
      "Asthma only",
      "Pneumonia"
    ],
    correctAnswer: 1,
    explanation: "Cardiac-induced pulmonary edema: heart failure causes fluid backup into lungs - presents as chest pain + respiratory distress. CHF history, crackles, pink frothy sputum classic. Treat with high-flow O2, upright position, CPAP if available, rapid transport.",
    category: "scenario",
    difficulty: "medium",
    tags: ["pulmonary edema", "CHF", "integrated assessment"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - Cardiogenic Pulmonary Edema Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-integrated-diabetic-trauma-001",
    module: 7,
    chapter: 16,
    scenario: "Single-vehicle crash, patient confused and combative. Glucose is 45 mg/dL. Minor airbag abrasions only, no other trauma found.",
    question: "Most likely sequence of events:",
    options: [
      "Crash caused confusion",
      "Hypoglycemia caused altered mental status leading to crash - medical cause of trauma",
      "Patient is intoxicated",
      "Head injury from crash"
    ],
    correctAnswer: 1,
    explanation: "Medical cause of trauma: hypoglycemia, seizure, stroke, MI can cause crashes. Low glucose explains confusion. Treat hypoglycemia, reassess for trauma. Document both medical and trauma aspects. Always consider medical causes in unexplained single-vehicle crashes.",
    category: "scenario",
    difficulty: "medium",
    tags: ["medical trauma", "hypoglycemia", "MVC", "integrated care"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - Medical Cause of Trauma Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-integrated-overdose-trauma-001",
    module: 7,
    chapter: 19,
    scenario: "Overdose patient is found unresponsive at bottom of stairs with head injury. Respiratory rate is 6/min, pinpoint pupils.",
    question: "What must you address first?",
    options: [
      "Head injury",
      "Respiratory failure from overdose - immediate life threat",
      "Pupils",
      "History of fall"
    ],
    correctAnswer: 1,
    explanation: "Overdose + trauma: address immediate life threats first. RR 6/min = respiratory failure - assist ventilations immediately, then naloxone per protocol. Then address trauma with c-spine precautions. Hypoxia kills faster than head injury with adequate breathing.",
    category: "scenario",
    difficulty: "hard",
    tags: ["overdose", "trauma", "airway priority", "naloxone"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - Overdose With Trauma Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-integrated-geriatric-fall-001",
    module: 9,
    chapter: 32,
    scenario: "Elderly patient fell, has hip pain, but also has new-onset confusion not explained by pain. Glucose normal, no head injury visible.",
    question: "What should you consider?",
    options: [
      "Pain causes all confusion",
      "Medical cause may have caused fall (stroke, MI, infection) - assess beyond obvious injury",
      "Age explains confusion",
      "Hip fracture only concern"
    ],
    correctAnswer: 1,
    explanation: "Geriatric falls: always ask 'why did they fall?' - stroke, MI, dysrhythmia, infection, medication effects can cause falls. Don't assume fall is simple slip. Assess for medical causes - stroke exam, cardiac symptoms, infection signs. Treat both fall injuries and underlying cause.",
    category: "scenario",
    difficulty: "medium",
    tags: ["geriatric falls", "medical assessment", "stroke"],
    nremtDomain: "Special Patient Populations",
    nationalProtocolAlignment: "NHTSA 2022 - Geriatric Fall Assessment Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-integrated-pregnancy-trauma-001",
    module: 9,
    chapter: 31,
    scenario: "Pregnant patient (30 weeks) in MVC has abdominal pain and vaginal bleeding. Vital signs: BP 90/60, HR 120. Patient states 'I'm fine, just worried about baby.'",
    question: "What is critical to understand?",
    options: [
      "Mother is fine based on her statement",
      "Placental abruption possible - mother can compensate while fetus in distress, left lateral position, rapid transport",
      "Vaginal bleeding always normal in pregnancy",
      "No urgency needed"
    ],
    correctAnswer: 1,
    explanation: "Pregnancy trauma: placental abruption from blunt force causes fetal distress before maternal decompensation. Abdominal pain + vaginal bleeding + trauma = abruption until proven otherwise. Left lateral tilt (relieves vena cava compression), high-flow O2, rapid transport to facility with OB capability.",
    category: "scenario",
    difficulty: "hard",
    tags: ["pregnancy trauma", "placental abruption", "fetal distress"],
    nremtDomain: "Special Patient Populations",
    nationalProtocolAlignment: "NHTSA 2022 - Pregnancy Trauma Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-integrated-behavioral-medical-001",
    module: 7,
    chapter: 21,
    scenario: "Patient found running naked in street in winter, confused and aggressive. Skin is very cold. Glucose 110 mg/dL.",
    question: "Primary concern:",
    options: [
      "Purely psychiatric",
      "Severe hypothermia causing altered behavior - medical emergency",
      "Intoxication only",
      "Dementia"
    ],
    correctAnswer: 1,
    explanation: "Behavioral emergencies: always rule out medical causes. Hypothermia causes confusion, paradoxical undressing (removing clothes despite cold), combative behavior. Also consider hypoglycemia, hypoxia, head injury, stroke, infection. Treat hypothermia gently, protect from further cold.",
    category: "scenario",
    difficulty: "medium",
    tags: ["hypothermia", "behavioral emergency", "altered mental status"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - Hypothermia Behavioral Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-integrated-allergic-asthma-001",
    module: 7,
    chapter: 18,
    scenario: "Patient with known asthma is having severe respiratory distress after bee sting. Developing hives and tongue swelling in addition to wheezing.",
    question: "This represents:",
    options: [
      "Just asthma attack",
      "Anaphylaxis - systemic allergic reaction more serious than asthma alone",
      "Normal bee sting",
      "Asthma and allergy are unrelated"
    ],
    correctAnswer: 1,
    explanation: "Anaphylaxis: multi-system allergic reaction - respiratory distress + hives + angioedema indicates anaphylaxis, not just asthma. Needs epinephrine first (life-saving), then albuterol for bronchospasm. Anaphylaxis can be rapidly fatal. Aggressive treatment, rapid transport.",
    category: "scenario",
    difficulty: "medium",
    tags: ["anaphylaxis", "asthma", "multi-system", "epinephrine"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - Anaphylaxis vs Asthma Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-integrated-seizure-head-injury-001",
    module: 7,
    chapter: 16,
    scenario: "Patient had witnessed generalized seizure, now postictal. Bystanders report patient hit head during seizure. Large hematoma on forehead.",
    question: "How should you manage?",
    options: [
      "Treat seizure only",
      "C-spine precautions despite postictal state - head injury during seizure requires spinal assessment",
      "No spinal precautions needed",
      "Seizure patients can't have spinal injuries"
    ],
    correctAnswer: 1,
    explanation: "Seizure with head trauma: uncontrolled fall/movements during seizure can cause c-spine injury. Postictal altered mental status prevents reliable exam. Use c-spine precautions. Document seizure and trauma separately. Transport for seizure evaluation AND head injury assessment.",
    category: "scenario",
    difficulty: "medium",
    tags: ["seizure", "head injury", "c-spine", "trauma"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - Seizure With Trauma Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-integrated-infection-sepsis-001",
    module: 7,
    chapter: 15,
    scenario: "Patient with dialysis fistula has fever 102°F, infected-looking fistula site, HR 130, BP 85/50, altered mental status. RR 28.",
    question: "This presentation suggests:",
    options: [
      "Local infection only",
      "Sepsis/septic shock - systemic infection with organ dysfunction",
      "Normal for dialysis patients",
      "Dehydration only"
    ],
    correctAnswer: 1,
    explanation: "Sepsis: systemic inflammatory response to infection with organ dysfunction. Infection source + fever + tachycardia + hypotension + altered mental status + tachypnea = sepsis/septic shock. Time-critical - high-flow O2, position to improve perfusion, keep warm, rapid transport. Early recognition improves survival.",
    category: "scenario",
    difficulty: "hard",
    tags: ["sepsis", "septic shock", "infection", "organ dysfunction"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - Sepsis Recognition Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-integrated-chest-pain-gerd-001",
    module: 7,
    chapter: 15,
    scenario: "Patient has chest discomfort after large meal, describes as 'burning,' relieved by antacids. No cardiac history. Vitals normal. Patient wants to refuse transport.",
    question: "What should you advise?",
    options: [
      "Definitely just heartburn - refusal okay",
      "GERD and MI can present similarly - strongly encourage evaluation, can't rule out cardiac in field",
      "Give more antacids and leave",
      "Heartburn never needs evaluation"
    ],
    correctAnswer: 1,
    explanation: "Chest pain assessment: cannot definitively rule out MI in field. GERD and MI can present identically. Even if symptoms 'sound like' GERD, MI remains in differential. Encourage transport for 12-lead EKG, cardiac enzymes. Document education if patient refuses. Atypical MI presentations are common.",
    category: "scenario",
    difficulty: "medium",
    tags: ["chest pain", "GERD", "MI differential", "refusal"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - Chest Pain Assessment Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-integrated-stroke-glucose-001",
    module: 7,
    chapter: 17,
    scenario: "Patient has sudden right-sided weakness and slurred speech. Glucose is 38 mg/dL. After oral glucose, symptoms completely resolve.",
    question: "What does this teach?",
    options: [
      "Was definitely stroke",
      "Hypoglycemia can mimic stroke - always check glucose in stroke symptoms, may reveal treatable cause",
      "Glucose and stroke unrelated",
      "Oral glucose treats strokes"
    ],
    correctAnswer: 1,
    explanation: "Stroke mimics: hypoglycemia classic mimic of stroke - focal deficits, altered mental status. ALWAYS check glucose in suspected stroke - treatable cause. If symptoms resolve with glucose, was hypoglycemia not stroke. Still transport for evaluation - could have both conditions.",
    category: "scenario",
    difficulty: "medium",
    tags: ["stroke mimic", "hypoglycemia", "glucose check", "differential diagnosis"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - Stroke Mimic Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-integrated-burns-inhalation-001",
    module: 8,
    chapter: 23,
    scenario: "House fire victim has facial burns, singed nasal hairs, soot in mouth, and hoarse voice. Skin burns are only partial thickness to face and hands.",
    question: "Primary concern:",
    options: [
      "Skin burns",
      "Inhalation injury - airway burns can cause life-threatening swelling",
      "Pain management",
      "Infection"
    ],
    correctAnswer: 1,
    explanation: "Inhalation injury signs: facial burns, singed hairs, soot in airway, hoarse voice, stridor, dyspnea. Progressive airway swelling can completely obstruct airway. High-flow O2, position upright, monitor closely, rapid transport. Intubate early if available - swelling makes later intubation impossible.",
    category: "scenario",
    difficulty: "hard",
    tags: ["inhalation injury", "burns", "airway swelling"],
    nremtDomain: "Trauma",
    nationalProtocolAlignment: "NHTSA 2022 - Inhalation Injury Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-integrated-copd-pneumonia-001",
    module: 7,
    chapter: 14,
    scenario: "COPD patient has worsening dyspnea over 3 days, fever, productive cough with green sputum, decreased breath sounds right lower lobe.",
    question: "This likely represents:",
    options: [
      "Just COPD exacerbation",
      "Pneumonia causing COPD exacerbation - infection triggered respiratory crisis",
      "COPD and pneumonia are unrelated",
      "Normal for COPD"
    ],
    correctAnswer: 1,
    explanation: "COPD exacerbation triggers: infection (pneumonia, bronchitis) most common. Fever + productive sputum + decreased breath sounds + worsening dyspnea = pneumonia in COPD patient. Treat with O2 to correct hypoxia, position of comfort, transport. May need antibiotics, possible hospitalization.",
    category: "scenario",
    difficulty: "medium",
    tags: ["COPD", "pneumonia", "respiratory infection"],
    nremtDomain: "Medical Emergencies",
    nationalProtocolAlignment: "NHTSA 2022 - COPD Exacerbation Protocol",
    emtScopeCompliant: true,
    points: 3,
    timeEstimate: 75
  },
  {
    id: "scenario-integrated-ectopic-pregnancy-001",
    module: 9,
    chapter: 31,
    scenario: "A woman has severe lower abdominal pain, vaginal bleeding, missed period, positive pregnancy test, signs of shock. Denies possibility of pregnancy initially.",
    question: "You should suspect:",
    options: [
      "Normal menstruation",
      "Ectopic pregnancy - life-threatening internal bleeding",
      "Normal early pregnancy",
      "Appendicitis"
    ],
    correctAnswer: 1,
    explanation: "Ectopic pregnancy: pregnancy outside uterus (usually fallopian tube), ruptures causing severe internal bleeding. Abdominal pain + vaginal bleeding + positive pregnancy + shock = ectopic until proven otherwise. Life-threatening. Treat for shock, rapid transport to surgical facility. Patient may not know she's pregnant.",
    category: "scenario",
    difficulty: "hard",
    tags: ["ectopic pregnancy", "shock", "vaginal bleeding", "OB emergency"],
    nremtDomain: "Special Patient Populations",
    nationalProtocolAlignment: "NHTSA 2022 - Ectopic Pregnancy Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  },
  {
    id: "scenario-integrated-penetrating-chest-abdomen-001",
    module: 8,
    chapter: 26,
    scenario: "Gunshot wound with entrance wound in right lower chest and exit wound in left upper abdomen. Patient is tachycardic and hypotensive.",
    question: "You should be concerned about:",
    options: [
      "Chest injury only",
      "Multi-cavity penetration - both thoracic and abdominal injuries, possibly diaphragm",
      "Exit wound only matters",
      "Superficial injuries"
    ],
    correctAnswer: 1,
    explanation: "Penetrating trauma trajectory: bullet path matters. Entrance chest + exit abdomen = potential injuries to lungs, heart, liver, spleen, diaphragm, vessels. Multi-cavity wounds have high mortality. Seal chest wounds, treat for shock, rapid transport to trauma center. Don't probe wounds.",
    category: "scenario",
    difficulty: "hard",
    tags: ["penetrating trauma", "GSW", "multi-cavity", "trajectory"],
    nremtDomain: "Trauma",
    nationalProtocolAlignment: "NHTSA 2022 - Penetrating Multi-Cavity Protocol",
    emtScopeCompliant: true,
    points: 4,
    timeEstimate: 90
  }
];
